import { Specialty } from '@/types/index';

export const SPECIALTIES: Specialty[] = [
  {
    id: 'cardiology',
    name: 'Cardiology',
    slug: 'cardiology',
    description: 'Expert cardiac care with advanced interventional procedures',
    icon: '❤️',
    conditions: [
      'Heart Disease',
      'Hypertension',
      'Arrhythmias',
      'Heart Failure',
      'Valve Disease',
    ],
    procedures: [
      'Angioplasty',
      'Bypass Surgery',
      'Valve Replacement',
      'Pacemaker Implantation',
      'Heart Transplant',
    ],
    benefits: [
      'Advanced diagnostic facilities',
      'Experienced cardiologists',
      'Latest cardiac technologies',
      '24/7 critical care support',
    ],
    recoveryTime: '4-8 weeks',
  },
  {
    id: 'orthopedics',
    name: 'Orthopedics',
    slug: 'orthopedics',
    description: 'Bone and joint specialists for all orthopedic needs',
    icon: '🦴',
    conditions: [
      'Arthritis',
      'Fractures',
      'Joint Disorders',
      'Spine Issues',
      'Sports Injuries',
    ],
    procedures: [
      'Knee Replacement',
      'Hip Replacement',
      'Spine Surgery',
      'ACL Reconstruction',
      'Shoulder Surgery',
    ],
    benefits: [
      'Minimally invasive techniques',
      'World-class orthopedic surgeons',
      'Advanced rehabilitation',
      'Proven successful outcomes',
    ],
    recoveryTime: '3-6 months',
  },
  {
    id: 'oncology',
    name: 'Oncology',
    slug: 'oncology',
    description: 'Comprehensive cancer treatment and support services',
    icon: '🔬',
    conditions: [
      'Breast Cancer',
      'Lung Cancer',
      'Colorectal Cancer',
      'Ovarian Cancer',
      'Lymphoma',
    ],
    procedures: [
      'Chemotherapy',
      'Radiation Therapy',
      'Cancer Surgery',
      'Immunotherapy',
      'Targeted Therapy',
    ],
    benefits: [
      'Multimodal treatment approach',
      'Experienced oncologists',
      'Latest cancer therapies',
      'Personalized treatment plans',
    ],
    recoveryTime: '3-12 months',
  },
  {
    id: 'neurology',
    name: 'Neurology & Neurosurgery',
    slug: 'neurology',
    description: 'Neurological and neurosurgical expertise',
    icon: '🧠',
    conditions: [
      'Brain Tumors',
      'Parkinson\'s',
      'Alzheimer\'s',
      'Stroke',
      'Epilepsy',
    ],
    procedures: [
      'Brain Surgery',
      'Spine Surgery',
      'Deep Brain Stimulation',
      'Endovascular Treatment',
      'Stereotactic Surgery',
    ],
    benefits: [
      'Specialized neurological care',
      'Advanced imaging',
      'Experienced neurosurgeons',
      'Comprehensive rehabilitation',
    ],
    recoveryTime: '2-8 weeks',
  },
  {
    id: 'kidney-care',
    name: 'Kidney Care',
    slug: 'kidney-care',
    description: 'Specialized kidney and renal services',
    icon: '🫘',
    conditions: [
      'Chronic Kidney Disease',
      'Kidney Failure',
      'Glomerulonephritis',
      'Kidney Stones',
      'Diabetic Nephropathy',
    ],
    procedures: [
      'Kidney Transplant',
      'Dialysis',
      'Nephrectomy',
      'Lithotripsy',
      'Renal Artery Stenting',
    ],
    benefits: [
      'Expert nephrologists',
      'Transplant specialists',
      'Dialysis facilities',
      'Kidney preservation strategies',
    ],
    recoveryTime: '4-12 weeks',
  },
  {
    id: 'liver-care',
    name: 'Liver Care',
    slug: 'liver-care',
    description: 'Hepatology and liver transplant services',
    icon: '🏥',
    conditions: [
      'Cirrhosis',
      'Hepatitis',
      'Liver Failure',
      'Fatty Liver',
      'Liver Cancer',
    ],
    procedures: [
      'Liver Transplant',
      'Hepatectomy',
      'TIPS Procedure',
      'Ablation Therapy',
      'Liver Resection',
    ],
    benefits: [
      'Transplant specialists',
      'Advanced diagnostics',
      'ICU support',
      'Comprehensive care',
    ],
    recoveryTime: '6-12 weeks',
  },
  {
    id: 'ivf',
    name: 'IVF & Fertility',
    slug: 'ivf-fertility',
    description: 'Complete reproductive health and fertility solutions',
    icon: '👶',
    conditions: [
      'Infertility',
      'Endometriosis',
      'PCOS',
      'Low Sperm Count',
      'Recurrent Miscarriage',
    ],
    procedures: [
      'IVF',
      'ICSI',
      'Egg Freezing',
      'Embryo Transfer',
      'Surrogacy Services',
    ],
    benefits: [
      'High success rates',
      'Modern fertility labs',
      'Experienced embryologists',
      'Emotional support services',
    ],
    recoveryTime: '2-4 weeks',
  },
  {
    id: 'dental',
    name: 'Dental Tourism',
    slug: 'dental-tourism',
    description: 'Complete dental solutions with advanced technology',
    icon: '😁',
    conditions: [
      'Dental Cavities',
      'Gum Disease',
      'Missing Teeth',
      'Misalignment',
      'Discoloration',
    ],
    procedures: [
      'Implants',
      'Root Canal',
      'Cosmetic Dentistry',
      'Orthodontics',
      'Teeth Whitening',
    ],
    benefits: [
      'Expert dentists',
      'Advanced equipment',
      'Affordable costs',
      'Cosmetic excellence',
    ],
    recoveryTime: '1-6 months',
  },
  {
    id: 'cosmetic',
    name: 'Cosmetic Surgery',
    slug: 'cosmetic-surgery',
    description: 'Aesthetic and reconstructive surgical expertise',
    icon: '✨',
    conditions: [
      'Facial Aging',
      'Body Contouring',
      'Breast Concerns',
      'Hair Loss',
      'Scars',
    ],
    procedures: [
      'Facelift',
      'Liposuction',
      'Breast Augmentation',
      'Hair Transplant',
      'Rhinoplasty',
    ],
    benefits: [
      'Aesthetic specialists',
      'Natural-looking results',
      'Advanced techniques',
      'High patient satisfaction',
    ],
    recoveryTime: '2-6 weeks',
  },
  {
    id: 'eye-care',
    name: 'Eye Care',
    slug: 'eye-care',
    description: 'Comprehensive ophthalmology and vision correction',
    icon: '👁️',
    conditions: [
      'Cataracts',
      'Glaucoma',
      'Refractive Errors',
      'Retinal Diseases',
      'Dry Eye',
    ],
    procedures: [
      'LASIK Surgery',
      'Cataract Surgery',
      'Corneal Transplant',
      'Retinal Surgery',
      'Glaucoma Treatment',
    ],
    benefits: [
      'Expert ophthalmologists',
      'Latest laser technology',
      'High success rates',
      'Vision restoration',
    ],
    recoveryTime: '1-4 weeks',
  },
  {
    id: 'health-checkup',
    name: 'Health Checkups',
    slug: 'health-checkups',
    description: 'Preventive health screening and wellness packages',
    icon: '📋',
    conditions: [],
    procedures: [
      'Full Body Checkup',
      'Cardiac Screening',
      'Cancer Screening',
      'Diabetes Check',
      'Executive Health Package',
    ],
    benefits: [
      'Early disease detection',
      'Comprehensive assessment',
      'Preventive care focus',
      'Personalized health reports',
    ],
    recoveryTime: 'N/A',
  },
  {
    id: 'ayurveda',
    name: 'Wellness & Ayurveda',
    slug: 'wellness-ayurveda',
    description: 'Traditional and modern wellness programs',
    icon: '🌿',
    conditions: [
      'Stress',
      'Chronic Pain',
      'Digestive Issues',
      'Skin Conditions',
      'Sleep Disorders',
    ],
    procedures: [
      'Ayurvedic Treatment',
      'Yoga & Meditation',
      'Wellness Retreats',
      'Nutrition Counseling',
      'Spa & Rejuvenation',
    ],
    benefits: [
      'Holistic healing approach',
      'Traditional wisdom',
      'Stress reduction',
      'Long-term wellness',
    ],
    recoveryTime: 'Ongoing',
  },
];

export const getSpecialtyBySlug = (slug: string) => {
  return SPECIALTIES.find((s) => s.slug === slug);
};

export const getSpecialtyById = (id: string) => {
  return SPECIALTIES.find((s) => s.id === id);
};
